name: Build and release binaries

on:
  release:
    types:
      - published
      - edited

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Build for Linux amd64
        run: |
          make -C src clean
          make -C src mdox GOOS=linux GOARCH=amd64
          cp src/mdox mdox-${{ github.event.release.tag_name }}-linux-amd64

      - name: Build for Windows
        run: |
          make -C src clean
          make -C src mdox GOOS=windows GOARCH=amd64
          cp src/mdox mdox-${{ github.event.release.tag_name }}-windows-amd64.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mdox-${{ github.event.release.tag_name }}-*
